apiVersion: v2
name: workshop-test
description: A Helm chart for Kubernetes
type: application
dependencies:
  - name: red-hat-workshop
    repository: oci://ghcr.io/shiriga51/helm
    version: "1.0.0"
    alias: deploy1
version: 1.0.0
appVersion: "1.0.0"